version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/learnhub_dev
      - JWT_SECRET_KEY=default-dev-secret
    depends_on:
      - mongo

  course-service:
    build: ./course-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/learnhub_dev
      - RABBITMQ_HOST=rabbitmq
      - EVENT_EXCHANGE=learning_events
    depends_on:
      - mongo
      - rabbitmq

  quiz-service:
    build: ./quiz-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=sqlite:///quiz_service.db
      - JWT_SECRET_KEY=default-dev-secret
      - COURSE_SERVICE_URL=http://course-service:5001
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - course-service
      - rabbitmq

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"