version: "3.8"
services:
  user-service:
    image: ghcr.io/peja016/user-service:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME_1}
      - MONGO_PASSWORD=${MONGO_PASSWORD_1}
      - MONGO_HOST=${MONGO_HOST_1}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - COURSE_SERVICE_URL=http://course-service:5001/courses
      - QUIZ_SERVICE_URL=http://quiz-service:5002/quiz
      - PROGRESS_SERVICE_URL=http://progress-api:5003/progress

  course-service:
    image: ghcr.io/peja016/course-service:latest
    env_file:
      - .env
    ports:
      - "5001:5001"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME_2}
      - MONGO_PASSWORD=${MONGO_PASSWORD_2}
      - MONGO_HOST=${MONGO_HOST_2}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - EVENT_EXCHANGE=learning_events

  quiz-service:
    image: ghcr.io/peja016/quiz-service:latest
    env_file:
      - .env
    ports:
      - "5002:5002"
    environment:
      - TURSO_URL=${TURSO_URL}
      - TURSO_TOKEN=${TURSO_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - COURSE_SERVICE_URL=http://course-service:5001
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - course-service

  # -------------------------
  # Progress Worker
  # -------------------------
  progress-worker:
    build: ./progress-service
    image: ghcr.io/peja016/progress-service:latest
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      MONGO_URI: mongodb+srv://${USERNAME}:${PASSWORD}@${HOST}/?appName=ds
      DATABASE_NAME: ${DATABASE_NAME}
    restart: unless-stopped

  # -------------------------
  # Progress API
  # -------------------------
  progress-api:
    build: ./progress-api
    ports:
      - "5003:5003"
    environment:
      MONGO_URI: mongodb+srv://${USERNAME}:${PASSWORD}@${HOST}/?appName=ds
      DATABASE_NAME: ${DATABASE_NAME}
