apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-api
  template:
    metadata:
      labels:
        app: progress-api
    spec:
      containers:
        - name: progress-api
          image: pppeterliu/progress-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: progress-api
spec:
  selector:
    app: progress-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
